<h2 align='center'> Assignment 3 </h2>

In [1]:
import numpy as np

### Ques1. Create a numpy array starting from 2 till 50 with a stepsize of 3.

In [2]:
np.arange(2,51,3)

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47, 50])

### Ques2. Accept two lists of 5 elements each from the user. Convert them to numpy arrays. Concatenate these arrays and print it. Also sort these arrays and print it.

In [3]:
l1 = eval(input())
l2 = eval(input())

n1 = np.array(l1)
n2 = np.array(l2)

n3 = np.concatenate((n1,n2))
print("Concatenated arrays: ", n3)

n4 = np.sort(n3)
print("Sorted Arrays: ", n4)

[1,24,57,4,78]
[48,2,34,49,50]
Concatenated arrays:  [ 1 24 57  4 78 48  2 34 49 50]
Sorted Arrays:  [ 1  2  4 24 34 48 49 50 57 78]


### Ques3. Write a code snippet to find the dimensions of a ndarray and its size.

In [4]:
a = np.arange(12).reshape((3, 4)) # 3x4 matrix --- 2d array therefore: dimension is 2 
print(a)
print("\ndimension of ndarray: ", a.ndim)
print("shape of ndarray: ", a.shape)
print("size of ndarray: ", a.size)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

dimension of ndarray:  2
shape of ndarray:  (3, 4)
size of ndarray:  12


### Ques4. How to convert a 1D array into a 2D array? Demonstrate with the help of a code snippet

In [5]:
x = np.array([1, 2])
print("1d array: ", x.shape)

y = np.expand_dims(x, axis=0)
print("1d converted to 2d array: ", y.shape)

y = np.expand_dims(x, axis=1)
print("1d converted to 2d array: ", y.shape)

1d array:  (2,)
1d converted to 2d array:  (1, 2)
1d converted to 2d array:  (2, 1)


### Ques5. Consider two square numpy arrays. Stack them vertically and horizontally.

In [6]:
a = np.array([1,2,3])
b = np.array([4,5,6])

print('Horizontal Append:\n', np.hstack((a, b)))
print('\nVertical Append:\n', np.vstack((a, b)))

Horizontal Append:
 [1 2 3 4 5 6]

Vertical Append:
 [[1 2 3]
 [4 5 6]]


### Ques6. How to get unique items and counts of unique items?

In [7]:
x = [1,4,57,4,78,1,24,56,88]
print("Unique item: ", np.unique(x))
print("Count of unique item: ", len(np.unique(x)))

Unique item:  [ 1  4 24 56 57 78 88]
Count of unique item:  7
